env:
  browser: true
  commonjs: true
  es6: true
globals:
  echarts: false
  BMap: false
extends:
  - 'eslint:recommended'
  - 'google'
plugins:
  - compat
parserOptions:
  emcaVersion: 6
  ecmaFeatures:
    experimentalObjectRestSpread: true
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  require-jsdoc: off
  compat/compat: error
settings:
  polyfills:
    - fetch
